version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: db_catalog
    environment:
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog_db
      POSTGRES_USER: catalog_user
    volumes:
      - ./postgres_data:/var/lib/postgres
    ports:
      - "5435:5432"

volumes:
  postgres_data:
